name: Daily Agro Data Pipeline

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

# --- LA CORRECTION EST ICI ---
# On donne explicitement au robot le droit d'écrire (modifier) le dépôt
permissions:
  contents: write 
# -----------------------------

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Récupération du code
      uses: actions/checkout@v4 # <- Mise à jour (v3 -> v4)

    - name: 🐍 Installation de Python
      uses: actions/setup-python@v5 # <- Mise à jour (v4 -> v5)
      with:
        python-version: '3.10'

    - name: 📦 Installation des librairies
      run: |
        pip install -r requirements.txt

    - name: 🚀 Exécution du script de données
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: |
        python data_pipeline.py

    - name: 💾 Sauvegarde de la base de données
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f agri_data.db
        git commit -m "Mise à jour automatique des données boursières et NLP" || echo "Aucune nouvelle donnée"
        git push
